### ISSUE TITLE
[React Native] Can't find variable: self

### ISSUE THREAD

**Issue by paolospag** [VirgilSecurity/virgil-crypto-javascript#37]
Hello there,
I'm trying to use  just `virgil-crypto` and  `virgil-sdk` libraries in a React Native project without `e3kit`, but I'm encountering the following error when debug is disabled

`Cant' find variable: self` 
![Schermata 2019-05-17 alle 10 48 18](https://user-images.githubusercontent.com/35046292/57915892-0c64c600-7892-11e9-81fe-0e611fd575f7.png)

The error appears to come before I initialize the method `new VirgilCrypto()`, it already happens when I import the module with `import { VirgilCrypto } from 'virgil-crypto';`

If debug is active, the error goes away.
Any idea?

package.json
```json
  "dependencies": {
    "@virgilsecurity/key-storage-rn": "0.1.3",
    "buffer": "5.2.1",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-firebase": "5.3.1",
    "react-native-gesture-handler": "1.2.1",
    "react-native-gifted-chat": "0.8.2",
    "react-native-keychain": "3.1.3",
    "react-navigation": "3.9.2",
    "virgil-crypto": "3.2.2",
    "virgil-sdk": "5.2.3"
  },
```

**Comment by vadimavdeev** [comment]
`self` [was used](https://github.com/VirgilSecurity/virgil-crypto-javascript/commit/bb53b5e9588e4abf2faddba493974ba68aa1fbd3) to enable `virgil-crypto` working in WebWorkers. We'll see if we can handle react-native as well. There is a [similar issue](https://github.com/facebook/react-native/issues/5667) in react-native itself. Meanwhile you can try putting `global.self = global` before importing `virgil-crypto` as a workaround.

**Comment by paolospag** [comment]
hi @vadimavdeev 
your workaround solution doesn't work anyway, the error continues to appear.
I put this at the top of `App.js` file:
```jsx
import { Buffer } from 'buffer';
global.Buffer = Buffer;
global.self = global;
```

**Comment by vadimavdeev** [comment]
I'll see how I can fix this from the library side. If you could send me a minimal runnable project where I can reproduce the issue, that would be super useful.

**Comment by paolospag** [comment]
@vadimavdeev can you give me your email address?

**Comment by vadimavdeev** [comment]
@paolospag it's vadim@virgilsecurity.com

**Comment by paolospag** [comment]
@vadimavdeev I just sent you a package via WeTransfer
