### ISSUE TITLE
Failed to download Virgil Crypto Node.js Addon - which node version is supported by virgil-crypto?

### ISSUE THREAD

**Issue by atereshkov** [VirgilSecurity/virgil-crypto-javascript#60]
Hey. Which version of node is supported by the virgil-crypto package?
And is it possible to run this package on Firebase Cloud Functions with node 8?

I saw this issue https://github.com/VirgilSecurity/virgil-crypto-javascript/issues/7
and @vadimavdeev wrote 

> Currently, only versions 4.x - 6.x are supported.

So what about current situation?

**Comment by atereshkov** [comment]
OK so I've tried it on my own and it seems like it's working with node 8 on Firebase CF (package.json):
```
  "engines": {
    "node": "8"
  },
```

On my local machine I've installed nvm and used node v8.10.0:
1. Install [nvm](https://github.com/nvm-sh/nvm)
2. Install node 8.x:
nvm use 8.10.0
2. If you get "nvm is not compatible with the npm config "prefix" option: currently set to "/Users/user/.npm-global", then run:
nvm use --delete-prefix v8.10.0
3. Then re-install virgil-crypto:
npm install --save virgil-crypto

**Comment by vadimavdeev** [comment]
The latest stable version of this library - v3.2.6 currently -  supports Node.js from version 4 to 11. There is a pre-release version - v4.0.0-alpha - that is in development and supports Node.js from version 8 to potentially any newer version due to the use of WebAssembly.

**Comment by atereshkov** [comment]
Great to hear that @vadimavdeev, спасибо! :)

Btw, feel free to close this issue as I just posted some info on how to run it when you have node > latest supported version atm.
