### ISSUE TITLE
Problem with generating tokens

### ISSUE THREAD

**Issue by otarm** [VirgilSecurity/virgil-crypto-javascript#73]
When generating a token on the back-end side, virgilCrypto.importPrivateKey is throwing an exception :
`Error: Cannot use global instances if the 'resetGlobalInstances' function has been called or 'createGlobalInstances' function has not been called yet.`

Node Version: 12.12.0
Virgil Crypto Version: ^4.0.0-alpha.18
Virgil SDK Version: ^6.0.0-alpha.6

**Comment by snanovskyi** [comment]
Hey @otarm 👋
You need to initialize the library using `initCrypto` function:
```js
const { initCrypto, VirgilCrypto } = require('virgil-crypto');

const start = async () => {
  await initCrypto();

  // And now you can do this anywhere in your app
  const virgilCrypto = new VirgilCrypto();
  const privateKey = virgilCrypto.importPrivateKey(process.env.YOUR_PRIVATE_KEY);
};

start();
```

**Comment by otarm** [comment]
@snanovskyi  Thanks! It worked. It'll be better if you update documentation for v4.0

**Comment by psylinse** [comment]
You have a bug in your documentation: https://developer.virgilsecurity.com/docs/e3kit/get-started/generate-client-tokens/

That page is missing the import for `initCrypto` which led to a bit of confusion on my part :)

**Comment by xlwknx** [comment]
@psylinse
Thank you for pointing out and sorry for inconvenience. We'll fix it soon!
